# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\trpc.proto\"1\n\x03RPC\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x13\n\x04\x61rgs\x18\x02 \x01(\x0b\x32\x05.Args\"\x1e\n\x0c\x63hannel_data\x12\x0e\n\x06values\x18\x01 \x03(\x05\"\x1f\n\rchannel_data2\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x18\n\x07prepost\x12\r\n\x05value\x18\x01 \x03(\x05\"\x16\n\x05reply\x12\r\n\x05value\x18\x01 \x01(\t\"\x83\x04\n\x04\x41rgs\x12\x17\n\x0funique_ADC_name\x18\x0b \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\n \x01(\t\x12\x0c\n\x04port\x18\t \x01(\x05\x12\x1a\n\x12number_of_channels\x18\x08 \x01(\x05\x12\x12\n\ntimestamps\x18\x07 \x03(\x03\x12\x12\n\npresamples\x18\x06 \x01(\x05\x12\x13\n\x0bpostsamples\x18\x05 \x01(\x05\x12\x1d\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x0f.Args.DataEntry\x12\x1f\n\x05\x64\x61ta2\x18\x03 \x03(\x0b\x32\x10.Args.Data2Entry\x12$\n\x08pre_post\x18\x02 \x03(\x0b\x32\x12.Args.PrePostEntry\x12#\n\x07offsets\x18\x01 \x03(\x0b\x32\x12.Args.OffsetsEntry\x1a:\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.channel_data:\x02\x38\x01\x1a<\n\nData2Entry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.channel_data2:\x02\x38\x01\x1a\x38\n\x0cPrePostEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.prepost:\x02\x38\x01\x1a.\n\x0cOffsetsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32*\n\x07RPC_req\x12\x1f\n\x0cregister_ADC\x12\x05.Args\x1a\x06.reply\"\x00\x62\x06proto3')
)




_RPC = _descriptor.Descriptor(
  name='RPC',
  full_name='RPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='function_name', full_name='RPC.function_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='RPC.args', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=62,
)


_CHANNEL_DATA = _descriptor.Descriptor(
  name='channel_data',
  full_name='channel_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='channel_data.values', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=94,
)


_CHANNEL_DATA2 = _descriptor.Descriptor(
  name='channel_data2',
  full_name='channel_data2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='channel_data2.values', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=127,
)


_PREPOST = _descriptor.Descriptor(
  name='prepost',
  full_name='prepost',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='prepost.value', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=153,
)


_REPLY = _descriptor.Descriptor(
  name='reply',
  full_name='reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='reply.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=177,
)


_ARGS_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='Args.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Args.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Args.DataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=527,
)

_ARGS_DATA2ENTRY = _descriptor.Descriptor(
  name='Data2Entry',
  full_name='Args.Data2Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Args.Data2Entry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Args.Data2Entry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=589,
)

_ARGS_PREPOSTENTRY = _descriptor.Descriptor(
  name='PrePostEntry',
  full_name='Args.PrePostEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Args.PrePostEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Args.PrePostEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=647,
)

_ARGS_OFFSETSENTRY = _descriptor.Descriptor(
  name='OffsetsEntry',
  full_name='Args.OffsetsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Args.OffsetsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Args.OffsetsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=649,
  serialized_end=695,
)

_ARGS = _descriptor.Descriptor(
  name='Args',
  full_name='Args',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unique_ADC_name', full_name='Args.unique_ADC_name', index=0,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='addr', full_name='Args.addr', index=1,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='Args.port', index=2,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_of_channels', full_name='Args.number_of_channels', index=3,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='Args.timestamps', index=4,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='presamples', full_name='Args.presamples', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='postsamples', full_name='Args.postsamples', index=6,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='Args.data', index=7,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data2', full_name='Args.data2', index=8,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pre_post', full_name='Args.pre_post', index=9,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offsets', full_name='Args.offsets', index=10,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ARGS_DATAENTRY, _ARGS_DATA2ENTRY, _ARGS_PREPOSTENTRY, _ARGS_OFFSETSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=695,
)

_RPC.fields_by_name['args'].message_type = _ARGS
_ARGS_DATAENTRY.fields_by_name['value'].message_type = _CHANNEL_DATA
_ARGS_DATAENTRY.containing_type = _ARGS
_ARGS_DATA2ENTRY.fields_by_name['value'].message_type = _CHANNEL_DATA2
_ARGS_DATA2ENTRY.containing_type = _ARGS
_ARGS_PREPOSTENTRY.fields_by_name['value'].message_type = _PREPOST
_ARGS_PREPOSTENTRY.containing_type = _ARGS
_ARGS_OFFSETSENTRY.containing_type = _ARGS
_ARGS.fields_by_name['data'].message_type = _ARGS_DATAENTRY
_ARGS.fields_by_name['data2'].message_type = _ARGS_DATA2ENTRY
_ARGS.fields_by_name['pre_post'].message_type = _ARGS_PREPOSTENTRY
_ARGS.fields_by_name['offsets'].message_type = _ARGS_OFFSETSENTRY
DESCRIPTOR.message_types_by_name['RPC'] = _RPC
DESCRIPTOR.message_types_by_name['channel_data'] = _CHANNEL_DATA
DESCRIPTOR.message_types_by_name['channel_data2'] = _CHANNEL_DATA2
DESCRIPTOR.message_types_by_name['prepost'] = _PREPOST
DESCRIPTOR.message_types_by_name['reply'] = _REPLY
DESCRIPTOR.message_types_by_name['Args'] = _ARGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RPC = _reflection.GeneratedProtocolMessageType('RPC', (_message.Message,), dict(
  DESCRIPTOR = _RPC,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:RPC)
  ))
_sym_db.RegisterMessage(RPC)

channel_data = _reflection.GeneratedProtocolMessageType('channel_data', (_message.Message,), dict(
  DESCRIPTOR = _CHANNEL_DATA,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:channel_data)
  ))
_sym_db.RegisterMessage(channel_data)

channel_data2 = _reflection.GeneratedProtocolMessageType('channel_data2', (_message.Message,), dict(
  DESCRIPTOR = _CHANNEL_DATA2,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:channel_data2)
  ))
_sym_db.RegisterMessage(channel_data2)

prepost = _reflection.GeneratedProtocolMessageType('prepost', (_message.Message,), dict(
  DESCRIPTOR = _PREPOST,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:prepost)
  ))
_sym_db.RegisterMessage(prepost)

reply = _reflection.GeneratedProtocolMessageType('reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:reply)
  ))
_sym_db.RegisterMessage(reply)

Args = _reflection.GeneratedProtocolMessageType('Args', (_message.Message,), dict(

  DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), dict(
    DESCRIPTOR = _ARGS_DATAENTRY,
    __module__ = 'rpc_pb2'
    # @@protoc_insertion_point(class_scope:Args.DataEntry)
    ))
  ,

  Data2Entry = _reflection.GeneratedProtocolMessageType('Data2Entry', (_message.Message,), dict(
    DESCRIPTOR = _ARGS_DATA2ENTRY,
    __module__ = 'rpc_pb2'
    # @@protoc_insertion_point(class_scope:Args.Data2Entry)
    ))
  ,

  PrePostEntry = _reflection.GeneratedProtocolMessageType('PrePostEntry', (_message.Message,), dict(
    DESCRIPTOR = _ARGS_PREPOSTENTRY,
    __module__ = 'rpc_pb2'
    # @@protoc_insertion_point(class_scope:Args.PrePostEntry)
    ))
  ,

  OffsetsEntry = _reflection.GeneratedProtocolMessageType('OffsetsEntry', (_message.Message,), dict(
    DESCRIPTOR = _ARGS_OFFSETSENTRY,
    __module__ = 'rpc_pb2'
    # @@protoc_insertion_point(class_scope:Args.OffsetsEntry)
    ))
  ,
  DESCRIPTOR = _ARGS,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:Args)
  ))
_sym_db.RegisterMessage(Args)
_sym_db.RegisterMessage(Args.DataEntry)
_sym_db.RegisterMessage(Args.Data2Entry)
_sym_db.RegisterMessage(Args.PrePostEntry)
_sym_db.RegisterMessage(Args.OffsetsEntry)


_ARGS_DATAENTRY._options = None
_ARGS_DATA2ENTRY._options = None
_ARGS_PREPOSTENTRY._options = None
_ARGS_OFFSETSENTRY._options = None

_RPC_REQ = _descriptor.ServiceDescriptor(
  name='RPC_req',
  full_name='RPC_req',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=697,
  serialized_end=739,
  methods=[
  _descriptor.MethodDescriptor(
    name='register_ADC',
    full_name='RPC_req.register_ADC',
    index=0,
    containing_service=None,
    input_type=_ARGS,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RPC_REQ)

DESCRIPTOR.services_by_name['RPC_req'] = _RPC_REQ

# @@protoc_insertion_point(module_scope)
