# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from general import rpc_pb2 as rpc__pb2


class RPC_reqStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.register_ADC = channel.unary_unary(
        '/RPC_req/register_ADC',
        request_serializer=rpc__pb2.Args.SerializeToString,
        response_deserializer=rpc__pb2.reply.FromString,
        )


class RPC_reqServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def register_ADC(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RPC_reqServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'register_ADC': grpc.unary_unary_rpc_method_handler(
          servicer.register_ADC,
          request_deserializer=rpc__pb2.Args.FromString,
          response_serializer=rpc__pb2.reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'RPC_req', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
